name: xenops
description: "a civ clone using munificent's hauberk 'engine'"
environment:
  sdk: '^2.12.0'
dependencies:
  malison: '^0.13.0'
  piecemeal: '^1.0.0'
  path: any
dev_dependencies:
  build_runner: any
  build_web_compilers: any
